{-# LANGUAGE RecordWildCards,NamedFieldPuns #-}
module Database where

import qualified Data.Map as Map
import Data.Map (Map)
import Data.List

import Histogram
import Types

chainBlades =
  [ Equipment "Raging Teeth"          Weapon Neutral [Ragehunter] [Technique, Utility]
  , Equipment "Flight of the Shrike"  Weapon Neutral [Conditioning] [Technique, Mobility]
  , Equipment "Quillshot's Bonehooks" Weapon Neutral [Acidic] [Technique, Defensive]
  , Equipment "Winter Winds"          Weapon Frost   [Nimble] [Technique, Mobility]
  , Equipment "Pangar's Claws"        Weapon Frost   [WeightedStrikes] [Technique, Defensive]
  , Equipment "Destiny of Boreus"     Weapon Frost   [Conditioning] [Power, Defensive]
  , Equipment "Charred Blades"        Weapon Blaze   [Aetherhunter] [Technique, Defensive]
  , Equipment "Ember Blades"          Weapon Blaze   [EvasiveFury] [Technique, Mobility]
  , Equipment "Inferno's Fangs"       Weapon Blaze   [Overpower] [Power, Power]
  , Equipment "Thundering Cutters"    Weapon Shock   [AethericAttunement] [Technique, Power]
  , Equipment "Nayzaga's Reach"       Weapon Shock   [Barbed] [Utility, Mobility]
  , Equipment "Storm Blades"          Weapon Shock   [Energized] [Technique, Mobility]
  , Equipment "Kharabak's Wings"      Weapon Terra   [Bladestorm] [Technique, Mobility]
  , Equipment "Skarn's Malice"        Weapon Terra   [WeightedStrikes] [Technique, Defensive]
  , Equipment "Sovereign's Lash"      Weapon Terra   [Sharpened] [Power, Utility]
  , Equipment "Eyes of Night"         Weapon Umbral  [Cunning] [Technique, Utility]
  , Equipment "Stalker's Trap"        Weapon Umbral  [WildFrenzy] [Technique, Utility]
  , Equipment "Valomyr's Revenge"     Weapon Radiant [Aetherhunter] [Power, Utility]
  , Equipment "Fangs of Dawn"         Weapon Radiant [Cunning] [Technique, Power]
  , Equipment "Electric Cruelties"    Weapon Shock   [Bond] [Prismatic, Prismatic]
  ]

pikes =
  [ Equipment "Raging Cruelty"       Weapon Neutral [Ragehunter] [Technique, Utility]
  , Equipment "Scream of the Shrike" Weapon Neutral [Conditioning] [Technique, Mobility]
  , Equipment "Quillshot's Javelin"  Weapon Neutral [Acidic] [Technique, Defensive]
  , Equipment "Revolution of Boreus" Weapon Frost   [Conditioning] [Power, Defensive]
  , Equipment "Winter Vortex"        Weapon Frost   [Nimble] [Technique, Mobility]
  , Equipment "Pangar's Tooth"       Weapon Frost   [WeightedStrikes] [Technique, Defensive]
  , Equipment "Skarn's Spite"        Weapon Terra   [WeightedStrikes] [Technique, Defensive]
  , Equipment "Kharabak's Sting"     Weapon Terra   [Bladestorm] [Technique, Mobility]
  , Equipment "Sovereign's Sorrow"   Weapon Terra   [Sharpened] [Power, Utility]
  , Equipment "Charred Spear"        Weapon Blaze   [Aetherhunter] [Technique, Defensive]
  , Equipment "Ember Pike"           Weapon Blaze   [EvasiveFury] [Technique, Mobility]
  , Equipment "Inferno's Arrow"      Weapon Blaze   [Overpower] [Power, Power]
  , Equipment "Thundering Spear"     Weapon Shock   [AethericAttunement] [Technique, Power]
  , Equipment "Nayzaga's Fang"       Weapon Shock   [Barbed] [Technique, Utility]
  , Equipment "Storm Pike"           Weapon Shock   [Energized] [Technique, Mobility]
  , Equipment "Gyre of Night"        Weapon Umbral  [Cunning] [Technique, Utility]
  , Equipment "Stalker's Spike"      Weapon Umbral  [WildFrenzy] [Technique, Utility]
  , Equipment "Valomyr's Hope"       Weapon Radiant [Aetherhunter] [Power, Utility]
  , Equipment "Spire of Dawn"        Weapon Radiant [Cunning] [Technique, Power]
  , Equipment "The Godhand"          Weapon Radiant [] [Technique, Power]
  , Equipment "The Conductor"        Weapon Shock   [Bond] [Prismatic, Prismatic]
  ]


strikers =
  [ Equipment "Raging Fists"          Weapon Neutral [Ragehunter]  [Technique, Utility]
  , Equipment "Fists of the Shrike"   Weapon Neutral [Conditioning]  [Technique, Mobility]
  , Equipment "Quillshot's Shredders" Weapon Neutral [Acidic]  [Technique, Defensive]
  , Equipment "Charred Hands"         Weapon Blaze   [Aetherhunter]  [Technique, Defensive]
  , Equipment "Ember Fists"           Weapon Blaze   [EvasiveFury]  [Technique, Mobility]
  , Equipment "Inferno's Flames"      Weapon Blaze   [Overpower]  [Power, Power]
  , Equipment "Winter Wolves"         Weapon Frost   [Nimble]  [Technique, Mobility]
  , Equipment "Pangar's Punishers"    Weapon Frost   [KnockoutKing]  [Technique, Defensive]
  , Equipment "Brawlers of Boreus"    Weapon Frost   [Conditioning]  [Power, Defensive]
  , Equipment "Thundering Bolts"      Weapon Shock   [AethericAttunement]  [Technique, Power]
  , Equipment "Nayzaga's Shockers"    Weapon Shock   [Savagery]  [Technique, Utility]
  , Equipment "Storm Breakers"        Weapon Shock   [AethericAttunement]  [Technique, Mobility]
  , Equipment "Skarn's Smashers"      Weapon Terra   [KnockoutKing]  [Technique, Defensive]
  , Equipment "Kharabak's Pincers"    Weapon Terra   [Bladestorm]  [Technique, Mobility]
  , Equipment "Sovereign's Sceptres"  Weapon Terra   [Sharpened]  [Power, Utility]
  , Equipment "Hands of Night"        Weapon Umbral  [Cunning]  [Technique, Utility]
  , Equipment "Stalker's Scorn"       Weapon Umbral  [WildFrenzy]  [Technique, Utility]
  , Equipment "Valomyr's Visions"     Weapon Radiant [Aetherhunter]  [Power, Utility]
  , Equipment "Hands of Dawn"         Weapon Radiant [Cunning]  [Technique, Power]
  , Equipment "Mistral Currents"      Weapon Shock   [Bond]  [Prismatic, Prismatic]

  , Equipment "Legendary Charred Hands"    Weapon Blaze [Aetherhunter] [Prismatic, Prismatic]
  , Equipment "Legendary Ember Fists"      Weapon Blaze [EvasiveFury]  [Prismatic, Prismatic]
  , Equipment "Legendary Inferno's Flames" Weapon Blaze [Overpower]    [Prismatic, Prismatic]
  ]

hammers =
  [ Equipment "Raging Crash"  Weapon Neutral  [Ragehunter]  [Power, Utility]
  , Equipment "Fall of the Shrike"  Weapon Neutral  [Conditioning]  [Power, Mobility]
  , Equipment "Quillshot's Roar"  Weapon Neutral  [Acidic]  [Power, Defensive]
  , Equipment "Skarn's Vengeance"  Weapon Terra [KnockoutKing]  [Power, Defensive]
  , Equipment "Charred Crusher"  Weapon Blaze [Aetherhunter]  [Power, Power]
  , Equipment "Ember Maul"  Weapon Blaze [EvasiveFury]  [Power, Mobility]
  , Equipment "Winter Squall"  Weapon Frost [Nimble]  [Power, Mobility]
  , Equipment "Thundering Maul"  Weapon Shock [AethericAttunement]  [Power, Defensive]
  , Equipment "Nayzaga's Charge"  Weapon Shock [Savagery]  [Power, Utility]
  , Equipment "Pangar's Rampage"  Weapon Frost [KnockoutKing]  [Power, Defensive]
  , Equipment "Inferno's Burden"  Weapon Blaze [Overpower]  [Power, Power]
  , Equipment "Storm Hammer"  Weapon Shock [AethericAttunement]  [Power, Mobility]
  , Equipment "Kharabak's Jaw"  Weapon Terra [Deconstruction]  [Power, Technique]
  -- , Equipment "Break of Dawn"  Weapon Radiant [Cunning]  [Power, Mobility]
  -- , Equipment "Fall of Night"  Weapon Umbral [Cunning]  [Power, Utility]
  , Equipment "Sovereign's Grudge"  Weapon Terra [Sharpened]  [Power, Utility]
  -- , Equipment "Stalker's Price"  Weapon Umbral [WildFrenzy]  [Technique, Utility]
  , Equipment "Valomyr's Burden"  Weapon Radiant [Aetherhunter]  [Power, Utility]
  , Equipment "Brutality of Boreus"  Weapon Frost [Conditioning]  [Power, Defensive]
  , Equipment "Galvanic Impact"  Weapon Shock [Bond]  [Prismatic, Prismatic]
  ]


helms =
  [ Equipment "Boreal Epiphany" Helm Frost [Conditioning] [Utility]
  , Equipment "Brow of Ice" Helm Frost [KnockoutKing] [Power]
  , Equipment "Crest of Valour" Helm Radiant [Lucent] [Power]
  , Equipment "Dark Watch" Helm Umbral [Rage] [Power]
  , Equipment "Draskscale Helmet" Helm Shock [AethericAttunement] [Power]
  , Equipment "Eye of the Swarm" Helm Terra [ShellshockResist] [Mobility]
  , Equipment "Fiery Helm" Helm Blaze [EvasiveFury] [Mobility]
  , Equipment "Gnasher Cap" Helm Neutral [Bloodless] [Defensive]
  , Equipment "Guise of the Rift" Helm Umbral [AethericAttunement] [Utility]
  , Equipment "Hellplate Casque" Helm Blaze [Ragehunter] [Technique]
  , Equipment "Lightning Helm" Helm Shock [Energized] [Technique]
  , Equipment "Light's Crown" Helm Radiant [Conduit] [Technique]
  , Equipment "Quillspike Mask" Helm Neutral [Savagery] [Defensive]
  , Equipment "Shocking Gaze" Helm Shock [Medic] [Utility]
  , Equipment "Shrikedown Helm" Helm Neutral [Evasion] [Technique]
  , Equipment "Sight of Stone" Helm Terra [Tough] [Defensive]
  , Equipment "Skraevwing Helmet" Helm Frost [FleetFooted] [Mobility]
  , Equipment "Visage of Thorns" Helm Terra [Agility] [Technique]
  , Equipment "Volcanic Helm" Helm Blaze [Fireproof] [Defensive]
  -- , Equipment "Malkarion's Sight" Helm Shock [Grace] [Mobility]
  ]

bodyArmors =
  [ Equipment "Aegis of Valour" BodyArmor Radiant [NineLives] [Power]
  , Equipment "Boreal Resolve" BodyArmor Frost [Rage] [Defensive]
  , Equipment "Core of Ice" BodyArmor Frost [Fortress] [Power]
  , Equipment "Dark Marrow" BodyArmor Umbral [Rage] [Power]
  , Equipment "Draskscale Plate" BodyArmor Shock [AethericAttunement] [Power]
  , Equipment "Fiery Breastplate" BodyArmor Blaze [EvasiveFury] [Mobility]
  , Equipment "Gnasher Cloak" BodyArmor Neutral [Tough] [Defensive]
  , Equipment "Heart of Stone" BodyArmor Terra [Guardian] [Defensive]
  , Equipment "Hellplate Cuirass" BodyArmor Blaze [Molten] [Technique]
  , Equipment "Lightning Plate" BodyArmor Shock [Energized] [Mobility]
  , Equipment "Light's Virtue" BodyArmor Radiant [Conduit] [Utility]
  , Equipment "Mantle of the Rift" BodyArmor Umbral [Conduit] [Utility]
  , Equipment "Mantle of Thorns" BodyArmor Terra [Predator] [Utility]
  , Equipment "Quillspike Jacket" BodyArmor Neutral [Savagery] [Technique]
  , Equipment "Shell of the Swarm" BodyArmor Terra [Bladestorm] [Technique]
  , Equipment "Shocking Heart" BodyArmor Shock [Medic] [Defensive]
  , Equipment "Shrikedown Plate" BodyArmor Neutral [Evasion] [Mobility]
  , Equipment "Skraevwing Jacket" BodyArmor Frost [Adrenaline] [Mobility]
  , Equipment "Volcanic Aegis" BodyArmor Blaze [Aetherhunter] [Utility]
  -- , Equipment "Malkarion's Soul" BodyArmor Shock [Aetherhunter] [Technique]
  ]

gauntlets =
  [ Equipment "Arms of Ice" Gauntlet Frost [KnockoutKing] [Defensive]
  , Equipment "Boreal Might" Gauntlet Frost [Rage] [Power]
  , Equipment "Clutches of the Swarm" Gauntlet Terra [Conditioning] [Mobility]
  , Equipment "Dark Embrace" Gauntlet Umbral [Medic] [Utility]
  , Equipment "Draskscale Gauntlets" Gauntlet Shock [Sharpened] [Utility]
  , Equipment "Fiery Gauntlets" Gauntlet Blaze [Fireproof] [Technique]
  , Equipment "Gauntlets of the Rift" Gauntlet Umbral [Evasion] [Mobility]
  , Equipment "Gauntlets of Valour" Gauntlet Radiant [Lucent] [Defensive]
  , Equipment "Gnasher Grips" Gauntlet Neutral [Ragehunter] [Power]
  , Equipment "Grasp of Thorns" Gauntlet Terra [EvasiveFury] [Power]
  , Equipment "Hellplate Bracers" Gauntlet Blaze [Molten] [Power]
  , Equipment "Lightning Gloves" Gauntlet Shock [Insulated] [Mobility]
  , Equipment "Light's Refuge" Gauntlet Radiant [Conduit] [Technique]
  , Equipment "Might of Stone" Gauntlet Terra [Fortress] [Defensive]
  , Equipment "Quillspike Grips" Gauntlet Neutral [Barbed] [Technique]
  , Equipment "Shocking Grasp" Gauntlet Shock [AethericAttunement] [Utility]
  , Equipment "Shrikedown Gloves" Gauntlet Neutral [WeightedStrikes] [Mobility]
  , Equipment "Skraevwing Gloves" Gauntlet Frost [Warmth] [Mobility]
  , Equipment "Volcanic Grips" Gauntlet Blaze [Rage] [Utility]
  -- , Equipment "Malkarion's Grasp" Gauntlet Shock [Predator] [Technique]
  ]

bootss =
  [ Equipment "Boreal March" Boots Frost [Iceborne] [Technique]
  , Equipment "Dance of the Swarm" Boots Terra [Conditioning] [Power]
  , Equipment "Dark Path" Boots Umbral [NineLives] [Utility]
  , Equipment "Draskscale Greaves" Boots Shock [FleetFooted] [Utility]
  , Equipment "Feet of Ice" Boots Frost [Warmth] [Defensive]
  , Equipment "Fiery Greaves" Boots Blaze [Evasion] [Defensive]
  , Equipment "Gnasher Treads" Boots Neutral [Tough] [Power]
  , Equipment "Greaves of Valour" Boots Radiant [Aetherhunter] [Utility]
  , Equipment "Hellplate Greaves" Boots Blaze [Fortress] [Power]
  , Equipment "Lightning Boots" Boots Shock [AethericFrenzy] [Mobility]
  , Equipment "Light's Walk" Boots Radiant [Agility] [Mobility]
  , Equipment "Pillars of Stone" Boots Terra [Guardian] [Defensive]
  , Equipment "Quillspike Boots" Boots Neutral [ShellshockResist] [Technique]
  , Equipment "Shocking Stride" Boots Shock [Insulated] [Defensive]
  , Equipment "Shrikedown Greaves" Boots Neutral [Bloodless] [Mobility]
  , Equipment "Skraevwing Boots" Boots Frost [Adrenaline] [Utility]
  , Equipment "Stride of Thorns" Boots Terra [Predator] [Utility]
  , Equipment "Striders of the Rift" Boots Umbral [Conduit] [Mobility]
  , Equipment "Volcanic Treads" Boots Blaze [Rage] [Power]
  -- , Equipment "Malkarion's March" Boots Shock [Aetherhunter] [Technique]
  ]

lanterns =
  [ Equipment "Any Lantern" Lantern Neutral [] [Utility]
  ]
