{-# LANGUAGE RecordWildCards,NamedFieldPuns #-}
module Database where

import qualified Data.Map as Map
import Data.Map (Map)
import Data.List

import Histogram
import Types

weapons = hammers

hammers =
  [ Equipment "Raging Crash"  Weapon Neutral  [Ragehunter]  [Power, Utility]
  , Equipment "Fall of the Shrike"  Weapon Neutral  [Conditioning]  [Power, Mobility]
  , Equipment "Quillshot's Roar"  Weapon Neutral  [Acidic]  [Power, Defensive]
  , Equipment "Skarn's Vengeance"  Weapon Terra [KnockoutKing]  [Power, Defensive]
  , Equipment "Charred Crusher"  Weapon Blaze [Aetherhunter]  [Power, Power]
  , Equipment "Ember Maul"  Weapon Blaze [EvasiveFury]  [Power, Mobility]
  , Equipment "Winter Squall"  Weapon Frost [Nimble]  [Power, Mobility]
  , Equipment "Thundering Maul"  Weapon Shock [AethericAttunement]  [Power, Defensive]
  , Equipment "Nayzaga's Charge"  Weapon Shock [Savagery]  [Power, Utility]
  , Equipment "Pangar's Rampage"  Weapon Frost [KnockoutKing]  [Power, Defensive]
  , Equipment "Inferno's Burden"  Weapon Blaze [Overpower]  [Power, Power]
  , Equipment "Storm Hammer"  Weapon Shock [AethericAttunement]  [Power, Mobility]
  , Equipment "Kharabak's Jaw"  Weapon Terra [Deconstruction]  [Power, Technique]
  , Equipment "Break of Dawn"  Weapon Radiant [Cunning]  [Power, Mobility]
  , Equipment "Fall of Night"  Weapon Umbral [Cunning]  [Power, Utility]
  , Equipment "Sovereign's Grudge"  Weapon Terra [Sharpened]  [Power, Utility]
  , Equipment "Stalker's Price"  Weapon Umbral [WildFrenzy]  [Technique, Utility]
  , Equipment "Valomyr's Burden"  Weapon Radiant [Aetherhunter]  [Power, Utility]
  , Equipment "Brutality of Boreus"  Weapon Frost [Conditioning]  [Power, Defensive]
  , Equipment "Galvanic Impact"  Weapon Shock [Bond]  [Prismatic, Prismatic]
  ]


strikers =
  [ Equipment "Raging Fists"  Weapon Neutral  [Ragehunter]  [Technique, Utility]
  , Equipment "Fists of the Shrike"  Weapon Neutral  [Conditioning]  [Technique, Mobility]
  , Equipment "Quillshot's Shredders"  Weapon Neutral  [Acidic]  [Technique, Defensive]
  , Equipment "Skarn's Smashers"  Weapon Terra  [KnockoutKing]  [Technique, Defensive]
  , Equipment "Charred Hands"  Weapon Blaze  [Aetherhunter]  [Technique, Defensive]
  , Equipment "Winter Wolves"  Weapon Frost  [Nimble]  [Technique, Mobility]
  , Equipment "Ember Fists"  Weapon Blaze  [EvasiveFury]  [Technique, Mobility]
  , Equipment "Thundering Bolts"  Weapon Shock  [AethericAttunement]  [Technique, Power]
  , Equipment "Nayzaga's Shockers"  Weapon Shock  [Savagery]  [Technique, Utility]
  , Equipment "Pangar's Punishers"  Weapon Frost  [KnockoutKing]  [Technique, Defensive]
  , Equipment "Inferno's Flames"  Weapon Blaze  [Overpower]  [Power, Power]
  , Equipment "Storm Breakers"  Weapon Shock  [AethericAttunement]  [Technique, Mobility]
  , Equipment "Kharabak's Pincers"  Weapon Terra  [Bladestorm]  [Technique, Mobility]
  , Equipment "Hands of Dawn"  Weapon Radiant  [Cunning]  [Technique, Power]
  , Equipment "Hands of Night"  Weapon Umbral  [Cunning]  [Technique, Utility]
  , Equipment "Sovereign's Sceptres"  Weapon Terra  [Sharpened]  [Power, Utility]
  , Equipment "Stalker's Scorn"  Weapon Umbral  [WildFrenzy]  [Technique, Utility]
  , Equipment "Valomyr's Visions"  Weapon Radiant  [Aetherhunter]  [Power, Utility]
  , Equipment "Brawlers of Boreus"  Weapon Frost  [Conditioning]  [Power, Defensive]
  , Equipment "Mistral Currents"  Weapon Shock  [Bond]  [Prismatic, Prismatic]
  ]


helms =
  [ Equipment "Lightning Helm" Helm Shock [Energized] [Technique]
  , Equipment "Skraevwing Helmet" Helm Frost [FleetFooted] [Mobility]
  , Equipment "Shrikedown Helm" Helm Neutral [Evasion] [Technique]
  , Equipment "Quillspike Mask" Helm Neutral [Savagery] [Defensive]
  , Equipment "Brow of Ice" Helm Frost [KnockoutKing] [Power]
  , Equipment "Shocking Gaze" Helm Shock [Medic] [Utility]
  , Equipment "Eye of the Swarm" Helm Terra [ShellshockResist] [Mobility]
  , Equipment "Hellplate Casque" Helm Blaze [Ragehunter] [Technique]
  , Equipment "Gnasher Cap" Helm Neutral [Bloodless] [Defensive]
  , Equipment "Fiery Helm" Helm Blaze [EvasiveFury] [Mobility]
  , Equipment "Draskscale Helmet" Helm Shock [AethericAttunement] [Power]
  , Equipment "Volcanic Helm" Helm Blaze [Fireproof] [Defensive]
  , Equipment "Crest of Valour" Helm Radiant [Lucent] [Power]
  , Equipment "Guise of the Rift" Helm Umbral [AethericAttunement] [Utility]
  , Equipment "Visage of Thorns" Helm Terra [Agility] [Technique]
  , Equipment "Boreal Epiphany" Helm Frost [Conditioning] [Utility]
  , Equipment "Sight of Stone" Helm Terra [Tough] [Defensive]
  , Equipment "Light's Crown" Helm Radiant [Conduit] [Technique]
  , Equipment "Dark Watch" Helm Umbral [Rage] [Power]
  , Equipment "Malkarion's Sight" Helm Shock [Grace] [Mobility]
  ]

bodyArmors =
  [ Equipment "Lightning Plate" BodyArmor Shock [Energized] [Mobility]
  , Equipment "Skraevwing Jacket" BodyArmor Frost [Adrenaline] [Mobility]
  , Equipment "Shrikedown Plate" BodyArmor Neutral [Evasion] [Mobility]
  , Equipment "Quillspike Jacket" BodyArmor Neutral [Savagery] [Technique]
  , Equipment "Core of Ice" BodyArmor Frost [Fortress] [Power]
  , Equipment "Shocking Heart" BodyArmor Shock [Medic] [Defensive]
  , Equipment "Shell of the Swarm" BodyArmor Terra [Bladestorm] [Technique]
  , Equipment "Hellplate Cuirass" BodyArmor Blaze [Molten] [Technique]
  , Equipment "Gnasher Cloak" BodyArmor Neutral [Tough] [Defensive]
  , Equipment "Fiery Breastplate" BodyArmor Blaze [EvasiveFury] [Mobility]
  , Equipment "Draskscale Plate" BodyArmor Shock [AethericAttunement] [Power]
  , Equipment "Volcanic Aegis" BodyArmor Blaze [Aetherhunter] [Utility]
  , Equipment "Aegis of Valour" BodyArmor Radiant [NineLives] [Power]
  , Equipment "Mantle of the Rift" BodyArmor Umbral [Conduit] [Utility]
  , Equipment "Mantle of Thorns" BodyArmor Terra [Predator] [Utility]
  , Equipment "Boreal Resolve" BodyArmor Frost [Rage] [Defensive]
  , Equipment "Heart of Stone" BodyArmor Terra [Guardian] [Defensive]
  , Equipment "Light's Virtue" BodyArmor Radiant [Conduit] [Utility]
  , Equipment "Dark Marrow" BodyArmor Umbral [Rage] [Power]
  , Equipment "Malkarion's Soul" BodyArmor Shock [Aetherhunter] [Technique]
  ]

gauntlets =
  [ Equipment "Lightning Gloves" Gauntlet Shock [Insulated] [Mobility]
  , Equipment "Skraevwing Gloves" Gauntlet Frost [Warmth] [Mobility]
  , Equipment "Shrikedown Gloves" Gauntlet Neutral [WeightedStrikes] [Mobility]
  , Equipment "Quillspike Grips" Gauntlet Neutral [Barbed] [Technique]
  , Equipment "Arms of Ice" Gauntlet Frost [KnockoutKing] [Defensive]
  , Equipment "Shocking Grasp" Gauntlet Shock [AethericAttunement] [Utility]
  , Equipment "Clutches of the Swarm" Gauntlet Terra [Conditioning] [Mobility]
  , Equipment "Hellplate Bracers" Gauntlet Blaze [Molten] [Power]
  , Equipment "Gnasher Grips" Gauntlet Neutral [Ragehunter] [Power]
  , Equipment "Fiery Gauntlets" Gauntlet Blaze [Fireproof] [Technique]
  , Equipment "Draskscale Gauntlets" Gauntlet Shock [Sharpened] [Utility]
  , Equipment "Volcanic Grips" Gauntlet Blaze [Rage] [Utility]
  , Equipment "Gauntlets of Valour" Gauntlet Radiant [Lucent] [Defensive]
  , Equipment "Gauntlets of the Rift" Gauntlet Umbral [Evasion] [Mobility]
  , Equipment "Grasp of Thorns" Gauntlet Terra [EvasiveFury] [Power]
  , Equipment "Boreal Might" Gauntlet Frost [Rage] [Power]
  , Equipment "Might of Stone" Gauntlet Terra [Fortress] [Defensive]
  , Equipment "Light's Refuge" Gauntlet Radiant [Conduit] [Technique]
  , Equipment "Dark Embrace" Gauntlet Umbral [Medic] [Utility]
  , Equipment "Malkarion's Grasp" Gauntlet Shock [Predator] [Technique]
  ]

bootss =
  [ Equipment "Lightning Boots" Boots Shock [AethericFrenzy] [Mobility]
  , Equipment "Skraevwing Boots" Boots Frost [Adrenaline] [Utility]
  , Equipment "Shrikedown Greaves" Boots Neutral [Bloodless] [Mobility]
  , Equipment "Quillspike Boots" Boots Neutral [ShellshockResist] [Technique]
  , Equipment "Feet of Ice" Boots Frost [Warmth] [Defensive]
  , Equipment "Shocking Stride" Boots Shock [Insulated] [Defensive]
  , Equipment "Dance of the Swarm" Boots Terra [Conditioning] [Power]
  , Equipment "Hellplate Greaves" Boots Blaze [Fortress] [Power]
  , Equipment "Gnasher Treads" Boots Neutral [Tough] [Power]
  , Equipment "Fiery Greaves" Boots Blaze [Evasion] [Defensive]
  , Equipment "Draskscale Greaves" Boots Shock [FleetFooted] [Utility]
  , Equipment "Volcanic Treads" Boots Blaze [Rage] [Power]
  , Equipment "Greaves of Valour" Boots Radiant [Aetherhunter] [Utility]
  , Equipment "Striders of the Rift" Boots Umbral [Conduit] [Mobility]
  , Equipment "Stride of Thorns" Boots Terra [Predator] [Utility]
  , Equipment "Boreal March" Boots Frost [Iceborne] [Technique]
  , Equipment "Pillars of Stone" Boots Terra [Guardian] [Defensive]
  , Equipment "Light's Walk" Boots Radiant [Agility] [Mobility]
  , Equipment "Dark Path" Boots Umbral [NineLives] [Utility]
  , Equipment "Malkarion's March" Boots Shock [Aetherhunter] [Technique]
  ]

lanterns =
  [ Equipment "Embermane's Rapture" Lantern Neutral [] [Utility]
  ]
